### ISSUE TITLE
Bot offline

### ISSUE THREAD

**Issue by PixieGoddess** [Voxel-Fox-Ltd/Profile#12]
Bot appears offline

**Comment by schlopp** [comment]
poggers

**Comment by schlopp** [comment]
hi vfl!!! i love women but ill flirt with men

**Comment by JoycesGitHub** [comment]
Well at least it wasn't big ben.

**Comment by 4Kaylum** [comment]
This issue is now resolved. Discord killing my bots yet again. Damn them to heck.
