### ISSUE TITLE
Max Profiles

### ISSUE THREAD

**Issue by Azrael170** [Voxel-Fox-Ltd/Profile#49]
It doesn't allow to change the value of the number from 0. The entire field is red and refuses to budge 
![image](https://github.com/Voxel-Fox-Ltd/Profile/assets/138235029/de4171cb-d2da-4e40-96af-a1cb7d207b58)

**Comment by 4Kaylum** [comment]
I am aware of this as of a few hours ago and have not had time to fix it at present. It will be fixed within the next 24 :)

**Comment by 4Kaylum** [comment]
Found some downtime much faster than I thought I'd be able to; this should be resolved for you as of now :)
