### ISSUE TITLE
Automatically verifying all profiles

### ISSUE THREAD

**Issue by dbartholomae** [Voxel-Fox-Ltd/Profile#5]
Hi there! I'm currently using the bot to manage learner profiles on my developer Discord. I would love to be able to just automatically verify all profiles instead of having to do it manually.
Unfortunately I don't know enough python to contribute this feature myself :-/

**Comment by 4Kaylum** [comment]
> I would love to be able to just automatically verify all profiles instead of having to do it manually.
If you edit your template (`,edittemplate name`) and click to edit the verification channel, you can write "continue" to unset the verification channel, and then all profiles will be automatically verified.

**Comment by dbartholomae** [comment]
Thanks! In that case I would offer to write a PR with a documentation update on all the things I wished where in the README xD

**Comment by 4Kaylum** [comment]
Go for it. 

There's quite a few things I'm yet to document in the repo - either becuase I think they're obvious, becuase they're written in the bot itself, or becuase I want to add more to them before making them significantly widespread.
